---

- hosts: localhost

  vars_files:
    - vars.yml
    
  become: true
  roles:
      - { role: common, tags: [ common ] }
      - { role: browsers, tags: [ browsers ] }
      - { role: programming, tags: [programming] }