---

- hosts: localhost

  vars_files:
    - vars.yml
    
  become: yes
  roles:

      - { role: common, tags: [ common ] }       
      # - { role: browsers, tags: [ browsers ] }
      # - { role: programming, tags: [programming] }
      # - { role: xfce_config, tags: [xfce] }