- name: Install programming core
  pacman:
    name:
      - yarn
      - tk
      - asdf-vm
      - neovim
      - docker
  become: yes

- name: Enable docker service, and not touch the state
  ansible.builtin.service:
    name: docker
    enabled: yes

- name: Start docker service, if not started
  ansible.builtin.service:
    name: docker
    state: started

- name: Install cuda
  pacman:
    name:
      - cuda
  become: yes



- name: Install IDEs
  pacman:
    name:
      - visual-studio-code-bin
      - pycharm-community-edition


# https://github.com/MicrosoftDocs/live-share/issues/224
- name: Jupyter VSCode requirements
  pacman:
    name:
      - gnome-keyring 
      - libsecret
  become: yes
