- name: Programming core
  pacman:
    name:
      - yarn
      - tk
      - asdf-vm
      - neovim
      - docker
  become: yes

- name: Programming apps
  pacman:
    name:
      - visual-studio-code-bin
      - pycharm-community-edition
  become: yes