- name: Install programming core
  pacman:
    name:
      - yarn
      - tk
      - asdf-vm
      - neovim
      - docker
  become: yes

- name: Install IDEs
  pacman:
    name:
      - visual-studio-code-bin
      - pycharm-community-edition


# https://github.com/MicrosoftDocs/live-share/issues/224
- name: Jupyter VSCode requirements
  pacman:
    name:
      - gnome-keyring 
      - libsecret
