- name: Install programming core
  pacman:
    name:
      - yarn
      - tk
      - neovim
      - fd # this is used by nvim for searching
      - docker
  become: yes

- name: Install aur programming core
  aur:
    name:
      - asdf-vm

- name: Enable docker service, and not touch the state
  ansible.builtin.service:
    name: docker
    enabled: yes

- block:
  - name: Start docker service, if not started
    service:
      name: docker
      state: started
    become: yes
  rescue:
    - fail:
        msg: >
          If this fails with dependency error, need to restart

- name: Install cuda
  pacman:
    name:
      - cuda
  become: yes

- name: Install nvidia-docker
  aur:
    name: nvidia-docker
    state: present

- name: Restart docker service, in all cases
  ansible.builtin.service:
    name: docker
    daemon_reload: true
    state: restarted
  become: yes

- name: Install IDEs
  aur:
    name:
      - visual-studio-code-bin
      - pycharm-community-edition

# https://github.com/MicrosoftDocs/live-share/issues/224
- name: Jupyter VSCode requirements
  pacman:
    name:
      - gnome-keyring
      - libsecret
  become: yes
