# # Web Browser

# Install browsers
- name: Install browsers
  aur:
      name: "{{ item }}"
      state: present
  with_items: "{{ browsers }}"


- name: Install opera ffmpeg codec
  pacman:
    name:
      - opera-ffmpeg-codecs
    state: present
  when: "'opera' in browsers"
  become: yes
    
