# # Web Browser

# Install browsers
- name: Install browsers
  aur:
    name: "{{ item }}"
    state: present
  with_items: "{{ browsers }}"

- name: Install opera ffmpeg codec
  aur:
    name:
      - opera-ffmpeg-codecs
    state: present
    extra_args: --noconfirm
    use: yay
  when: "'opera' in browsers"
