- name: Virtual Machine
  pacman:
    name:
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-dkms
  become: yes

# - name: Slack
#   pacman:
#     name:
#       - slack-desktop



