- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - vlc
    - gimp
    - git
    - tree
    - base-devel
   state: present

- name: Install archival utils
  pacman:
    name:
      - unrar
      - unzip
      - zip
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - curl
      - wget
    state: present

- name: Install theme
  ansible.builtin.command:
    cmd: echo y | yay -S zsh-theme-powerlevel10k
