- name: Check updates
  pacman: 
   update_cache: yes
   upgrade: yes

- import_tasks: core-apps.yml

# Install and configure zsh
- import_tasks: zsh.yml

# # Office
# - import_tasks:office.yml
#   when: install_office == True
  
# # AUR apps
# - import_tasks:aur.yml
#   when: use_aur == True

