

- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes
  become: true

- include: core-apps.yml

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True


- include: g810.yml


# # Office
# - include: office.yml
#   when: install_office == True
  


