

- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes
  become: true

- include: core-apps.yml

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# TODO: fix, doesn't work rn
# - name: Install g810 keyboard controller
#   command: yay -S g810-led --noconfirm --nocleanmenu --noeditmenu 

# # Office
# - include: office.yml
#   when: install_office == True
  


