# - name: install base-devel
#   pacman:
#     name:
#       - archlinux-keyring

# - name: check updates
#   pacman: 
#    update_cache: yes
#    upgrade: yes
#    force: yes

# - include: core-apps.yml

- include: fonts.yml


# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# # Office
# - include: office.yml
#   when: install_office == True
  
# # AUR apps
# - include: aur.yml
#   when: use_aur == True

