- name: Check updates
  pacman: 
   update_cache: yes
   upgrade: yes
  become: true

- import_tasks: apps.yml

# Install and configure zsh
- import_tasks: zsh.yml


# - import_tasks: g810.yml

# # Office
# - import_tasks:office.yml
#   when: install_office == True
  

