---

- name: Install zsh
  community.general.pacman:
   name: 
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
   state: present

- name: Install zsh-autosuggestion
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest:  ~/.zsh/zsh-autosuggestions
    single_branch: yes
    version: master

- name: Install fzf for zsh
  community.general.pacman:
   name: 
    - fzf
   state: present

- name: Change {{ username }}'s shell to zsh
  become: yes
  user:
   name: "{{ username }}"
   shell: /usr/bin/zsh

- name: Copy zsh dotfile
  copy: 
   src: user_home/.zshrc 
   dest: /home/{{ username }}/.zshrc
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--

- name: Check if p10k is installed 
  stat:
    path: /home/{{ username }}/.p10k.zsh
  register: result

- name: Install p10k
  aur:
      name: zsh-theme-powerlevel10k-git
      state: present
  when: not result.stat.exists

- name: Add to source
  command: echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
  when: not result.stat.exists

- name: Copy zsh p10k dotfile
  copy: 
   src: user_home/.p10k.zsh
   dest: /home/{{ username }}/.p10k.zsh
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--
  when: not result.stat.exists

- name: Change shell
  command: chsh -s /bin/zsh
  become: yes
  when: not result.stat.exists

