---

- name: install zsh
  community.general.pacman:
   name: 
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - zsh-autosuggestions
   state: present

- name: install fzf for zsh
  community.general.pacman:
   name: 
    - fzf
   state: present

- name: change "{{ username }}"'s shell to zsh
  become: yes
  user:
   name: "{{ username }}"
   shell: /usr/bin/zsh

- name: copy zsh dotfile
  copy: 
   src: user_home/.zshrc 
   dest: /home/{{ username }}/.zshrc
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--

- name: Check if p10k is installed 
  stat:
    path: /home/{{ username }}/.p10k.zsh
  register: result

- name: install p10k
  command: yay -S --noconfirm --noconfirm --nocleanmenu --noeditmenu zsh-theme-powerlevel10k-git
  command: echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
  when: not result.stat.exists

- name: copy zsh p10k dotfile
  copy: 
   src: user_home/.p10k.zsh
   dest: /home/{{ username }}/.p10k.zsh
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--


- name: change shell
  command: chsh -s /bin/zsh
  become: yes

