---

- name: install zsh
  community.general.pacman:
   name: 
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
    - zsh-autosuggestions
   state: present

- name: install fzf for zsh
  community.general.pacman:
   name: 
    - fzf
   state: present

- name: change "{{ username }}"'s shell to zsh
  become: yes
  user:
   name: "{{ username }}"
   shell: /usr/bin/zsh

- name: copy zsh dotfile
  copy: 
   src: user_home/.zshrc 
   dest: /home/{{ username }}/.zshrc
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--

- name: copy zsh p10k dotfile
  copy: 
   src: user_home/.p10k.zsh
   dest: /home/{{ username }}/.p10k.zsh
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--


